FROM       timn/fawkes-buildenv:f25-kinetic

RUN /bin/bash -c "source /opt/fawkes-buildenv/setup.bash && \
	/opt/fawkes-buildenv/get-fawkes-release -C /opt fawkes-robotino-2016-2.tar.bz2 &&\
	/opt/fawkes-buildenv/apply-patches -C /opt/fawkes-robotino -p1 -d fawkes /opt/fawkes-buildenv/patches.d/fawkes-core-*.patch &&\
	/opt/fawkes-buildenv/apply-patches -C /opt/fawkes-robotino -p1 /opt/fawkes-buildenv/patches.d/fawkes-robotino-*.patch &&\
	/opt/fawkes-buildenv/generic-build-flags -C /opt/fawkes-robotino &&\
	/opt/fawkes-buildenv/build -C /opt/fawkes-robotino &&\
	/opt/fawkes-buildenv/tweaks -C /opt/fawkes-robotino robotino-agent-2015 \
  "

