#!/bin/bash

CHANGE_DIR=
CONCURRENCY=$(nproc)

OPTS=$(getopt -o "C:j:" -- "$@")
if [ $? != 0 ]
then
    echo "Failed to parse parameters"
    exit 1
fi

eval set -- "$OPTS"
while true; do
  OPTION=$1
  OPTARG=$2
  case $OPTION in
    -C)                    CHANGE_DIR=$OPTARG;;
		-j)                    CONCURRENCY=$OPTARG;;
    --)                    shift; break;;
  esac
  shift
done

if [ -n "$CHANGE_DIR" ]; then pushd $CHANGE_DIR >/dev/null; fi

make -j$CONCURRENCY all gui ${VERBOSE:+VERBOSE=1} CFLAGS_MTUNE_NATIVE=
find . -name '.objs_*' -prune -exec rm -rf {} \;
find . -name '.deps_*' -prune -exec rm -rf {} \;


if [ -n "$CHANGE_DIR" ]; then popd >/dev/null; fi
