#!/bin/bash

set -e

SCRIPT_PATH=$(dirname $(readlink -f ${BASH_SOURCE[0]}))
source $SCRIPT_PATH/setup.bash

COMPONENT=${1:-NOT SET}

echo "Running component $COMPONENT"

case $COMPONENT in
	gazebo)
		echo "Running gzserver"
		gzserver $GAZEBO_WORLD_PATH || exit 11
		;;

	refbox)
		echo "Running llsf-refbox"
		$LLSF_REFBOX_DIR/bin/llsf-refbox || exit 21
		;;

	run-game)
		$SCRIPT_PATH/run-game
		;;

	fawkes)
		if [ -z "$META_PLUGIN" ]; then
			2>&1 echo "Meta plugin not set, aborting"
			exit 41
		fi
		LL=${LOG_LEVEL:-info}
		CONF=${CONFIG:-config.yaml}
		$FAWKES_DIR/bin/fawkes -c $CONF -L console -l $LL $META_PLUGIN || exit 42
		;;

	roscore)
		stdbuf -oL -eL roscore || exit 51
		;;

	roslaunch)
		if [ -z "$ROS_PACKAGE" ]; then
			2>&1 echo "ROS package not set, aborting"
			exit 61
		fi
		if [ -z "$ROS_LAUNCH_FILE" ]; then
			2>&1 echo "Launch file not set, aborting"
			exit 61
		fi
		echo "Launching $ROS_PACKAGE $ROS_LAUNCH_FILE"
		stdbuf -oL -eL roslaunch --screen --wait --skip-log-check --disable-title $ROS_PACKAGE $ROS_LAUNCH_FILE || exit 62
		;;

	*)
		echo "Unknown component"
		exit 1
    ;;
esac

echo "*** TERMINATED SUCCESSFULLY ***"
exit 0
